Bring into line with modern cetbuildtools use.

diff --git a/ups/setup_for_development b/ups/setup_for_development
--- a/ups/setup_for_development
+++ b/ups/setup_for_development
@@ -1,19 +1,13 @@
-# This is shamelessly cribbed from Ron Rechenmacher's ups bootstrap "setup"
+# NO USER-SERVICEABLE PARTS BELOW.
 #
-# REPLACE all occurances of TOYCMAKE with your product name in upper case
-#
-# This script sets up the environment for a developer working on framework.
-# It is not intended for any other purpose, and may cause problems in other environments.
+# There should be as little as possible here,
+# with most of the heavy lifting done by other small scripts
 #
 # When sourcing this file from a script, you may have to tell this
 # source file where it is via the fw_db shell (or env) variable.
 # I.e.:
 #    set fw_db=/some/path; source /some/path/this_file
 # or  fw_db=/some/path; . /some/path/this_file
-#
-# If TOYCMAKE_BUILD is undefined, it is set to whatever directory
-# you are in when this script is invoked.
-# $TOYCMAKE_BUILD/lib is added to LD_LIBRARY_PATH
 
 test $?shell = 1 && set ss=csh || ss=sh
 #echo Shell type is $ss.
@@ -21,31 +15,24 @@ test $?shell = 1 && set ss=csh || ss=sh
 # make some things similar. need to use set_ because sh builtin set would hide function set
 # Note: perhaps the trickiest thing in this file is the sh set_ function tries to return the same status
 #       as at the start of the function (which most likely is the result of a back-tick expression
-test "$ss" = csh && alias set_ set && alias vecho_ 'if ($?vv == 1) echo \!*' || eval 'vecho_() { test -n "${vv-}" && echo "$@";}'
-test "$ss" =  sh && eval 'set_() { ss=$?;for xx in "$@";do var=`expr "$xx" : "\([^=]*\)"`;val=`expr "$xx" : "[^=]*=\(.*\)"`;eval "$var=\"$val\"";done;return $ss; }'
-test "$ss" =  sh && eval 'setenv() { export $1;eval "$1=\"\${2-}\""; }' && eval 'source() { file=$1; shift; . $file "$@"; }' && eval 'unsetenv() { unset "$@"; }'
+test "$ss" = csh && alias set_ set && alias vecho_ 'if ($?vv == 1) echo \!*' || eval 'vecho_() { test -n "${vv-}" && echo "$@"; return 0; }'
+test "$ss" =  sh && eval 'set_() { sts=$?;for xx in "$@";do var=`expr "$xx" : "\([^=]*\)"`;val=`expr "$xx" : "[^=]*=\(.*\)"`;eval "$var=\"$val\"";done;return $sts; }'
+test "$ss" =  sh && eval 'setenv() { export $1;eval "$1=\"\${2-}\""; }; source() { file=$1; shift; . $file "$@"; }; unsetenv_() { unset "$@"; }'
 test "$ss" =  sh && eval 'tnotnull() { eval "test -n \"\${$1-}\""; }'                             && eval 'nullout() { "$@" >/dev/null 2>&1; }'
-test "$ss" = csh && alias tnotnull "eval '"'test $?'"\!* -eq 1' && eval '"'test -n "$'"\!*"'"'"'" && alias nullout "\!* >& /dev/null"
+test "$ss" = csh && alias tnotnull "eval '"'test $?'"\!* -eq 1' && eval '"'test -n "$'"\!*"'"'"'" && alias nullout "\!* >& /dev/null" && alias unsetenv_ unsetenv
+test "$ss" = csh && alias return exit
 
-set_ msg2='You MUST setup ups'
-tnotnull UPS_DIR || echo "$msg2"
+set_ msg1='ERROR: You MUST setup ups'
+test -z $UPS_DIR && ( echo ""; echo "$msg1"; echo "" ) && return
 
-# we setup dependent products here
-# note that we do not test for them first...
-# use setup -j to avoid pulling dependencies
-setup cetbuildtools v1_11_09
-#setup -j boost v1_45_0 -q gcc45
-setup gcc v4_5_1
-setup cmake
+set_ msg3='ERROR: You MUST specify either -o, -p, or -d'
+set_ msg4='Usage: setup_for_development <-d|-o|-p> <qualifier list>'
+test -z "$1" && ( echo ""; echo "$msg4"; echo "$msg3"; echo "" ) && return
 
-test $?shell = 1 && set ss=csh || ss=sh
-test "$ss" = csh && alias set_ set && alias vecho_ 'if ($?vv == 1) echo \!*' || eval 'vecho_() { test -n "${vv-}" && echo "$@";}'
-test "$ss" =  sh && eval 'set_() { ss=$?;for xx in "$@";do var=`expr "$xx" : "\([^=]*\)"`;val=`expr "$xx" : "[^=]*=\(.*\)"`;eval "$var=\"$val\"";done;return $ss; }'
-test "$ss" =  sh && eval 'setenv() { export $1;eval "$1=\"\${2-}\""; }' && eval 'source() { file=$1; shift; . $file "$@"; }' && eval 'unsetenv() { unset "$@"; }'
-
-# now is if we were passed a path or if not, if we can figure it out (maybe if we are interactive)
+# make sure we know where this script lives
+# now if we were passed a path or if not, we can figure it out (maybe if we are interactive)
 #   bash, zsh, ksh and tcsh pass params to a source file, csh does not. but someone will be writing csh scripts
-set_ msg='Please set shell or env. variable fw_db (to be the path to the framework source code). Fix this and other errors may go away.'
+set_ msg2='Please set shell or env. variable fw_db (to be the path to the framework source code). Fix this and other errors may go away.'
 tnotnull fw_db && set_ db=`sh -c "cd $fw_db >/dev/null 2>&1 && pwd"` && vecho_ 'setting db from fw_db variable' || set_ db=
 
 test -z "$db" && tnotnull BASH_SOURCE && set_ me=`dirname $BASH_SOURCE` && set_ db=`sh -c "cd $me >/dev/null 2>&1 && pwd"` && vecho_ 'setting db via BASH_SOURCE'
@@ -54,26 +41,56 @@ test -z "$db" && tnotnull BASH_SOURCE && set_ me=`dirname $BASH_SOURCE` && set_ 
 test -z "$db" -a "$ss" = csh && test $?history = 0 && set history=5  # make sure history 1 works
 test -z "$db" -a "$ss" = csh && set me=`history 1|sed 's/^[ 	0-9:]*//'` && test -n "$me" && set me=`dirname $me[2]` \
     && set db=`sh -c "cd $me >/dev/null 2>&1 && pwd"` && vecho_ 'setting db via interactive history'
-
-test -z "$db" && echo "$msg" || vecho_ "db=$db"
-test -n "$db" && setenv TOYCMAKE_SOURCE `dirname $db`
 #echo This script lives in $db
 
-tnotnull TOYCMAKE_BUILD && set_ thisdir=$TOYCMAKE_BUILD || set_ thisdir=`pwd`
-test -n "$thisdir" && setenv TOYCMAKE_BUILD $thisdir
-test -d "$thisdir/lib" || mkdir -p $thisdir/lib
-echo The working build directory is $thisdir
+test -z "$db" && echo "$msg2" || vecho_ "db=$db"
+test -n "$db" && setenv CETPKG_SOURCE `dirname $db`
 
-tnotnull TOYCMAKE_BUILD && setenv LD_LIBRARY_PATH `echo :${LD_LIBRARY_PATH}: | sed -e "s|:${TOYCMAKE_BUILD}/lib:|:|" -e 's|^:||;s|:$||'`; setenv LD_LIBRARY_PATH ${TOYCMAKE_BUILD}/lib:${LD_LIBRARY_PATH}
+# make sure we know the current directory
+setenv CETPKG_BUILD `pwd`
+#echo Build directory is $CETPKG_BUILD
 
-echo
-echo TOYCMAKE_SOURCE=$TOYCMAKE_SOURCE
-echo TOYCMAKE_BUILD=$TOYCMAKE_BUILD
-echo $thisdir/lib has been added to LD_LIBRARY_PATH
-echo
-echo LD_LIBRARY_PATH is now ${LD_LIBRARY_PATH}
+echo The working build directory is $CETPKG_BUILD
+echo The source code directory is $CETPKG_SOURCE
+
+set_ msg5='ERROR: setup of required products has failed'
+
+echo ----------- check this block for errors -----------------------
+set_ setup_fail="false"
+set_ exit_now="false"
+set_ cetb=` grep -e '^[ \t]*cetbuildtools' $CETPKG_SOURCE/ups/product_deps | grep  only_for_build| awk '{ print $1 }' `
+set_ cetv=` grep -e '^[ \t]*cetbuildtools' $CETPKG_SOURCE/ups/product_deps | grep  only_for_build| awk '{ print $2 }' `
+#echo Found $cetb $cetv
+setup -B $cetb $cetv
+test "$?" = 0 || set_ setup_fail="true"
+# now get the rest of the products
+set_ cmd="$CETBUILDTOOLS_DIR/bin/set_dev_products $CETPKG_SOURCE $CETPKG_BUILD $*"
+#echo Ready to run $cmd
+source `$cmd`
+test "$?" = 0 || set_ setup_fail="true"
+#echo "$cmd returned $setup_fail"
+test "$setup_fail" = "true" && echo "$msg5"
+test "$setup_fail" = "true" && set_ exit_now="true"
+test -e "$CETPKG_BUILD/diag_report" && cat $CETPKG_BUILD/diag_report
+echo ----------------------------------------------------------------
+
+test "${exit_now}" = "true" && test "$ss" = csh && unalias tnotnull nullout set_ vecho_ return
+test "${exit_now}" = "true" && unset ss db me thisdir msg1 msg2 msg3 msg4 msg5 setup_fail set_ setenv unsetenv_ tnotnull nullout vecho_
+test "${exit_now}" = "true" && return 1
+
+# add lib to LD_LIBRARY_PATH
+source $CETBUILDTOOLS_DIR/bin/set_dev_lib
+# add bin to path
+source $CETBUILDTOOLS_DIR/bin/set_dev_bin
+# set FHICL_FILE_PATH
+source $CETBUILDTOOLS_DIR/bin/set_dev_fhicl
+# set FW_SEARCH_PATH
+source $CETBUILDTOOLS_DIR/bin/set_dev_fwsearch
+
+# final sanity check and report
+source $CETBUILDTOOLS_DIR/bin/set_dev_check_report
 
 # cleanup before exiting
-test "$ss" = csh && unalias tnotnull nullout set_ vecho_
-unset ss msg db me thisdir py_ver
-unset set_ setenv unsetenv tnotnull source nullout vecho_
+test "$ss" = csh && unalias tnotnull nullout set_ vecho_ return
+unset ss db me thisdir msg1 msg2 msg3 msg4 msg5 setup_fail
+unset set_ setenv unsetenv_ tnotnull nullout vecho_
